version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - laravel
    ports:
      - "8080:8080"
    networks:
      - dev

  laravel:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: php:8.0-fpm
    container_name: laravel
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - database
    networks:
      - dev

  database:
    image: mariadb:10.7
    container_name: database
    volumes:
      - ./docker/config.cnf:/etc/mysql/conf.d/config.cnf
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - dev

networks:
  dev:
    driver: bridge
